Probamos levantar el csv origen
=

In [1]:
import pandas as pd

# Cargar el archivo CSV
#df = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8')

# Mostrar las primeras 5 filas
#print(df.head())

Ciudades
========

In [2]:
# CiudadSucursal
ciudades = ['CiudadSucursal']
todas_ciudades = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=ciudades)
ciudades_unicas = todas_ciudades.drop_duplicates().sort_values('CiudadSucursal').reset_index(drop=True)
ciudades_unicas['id_ciudad'] = ciudades_unicas.index + 1
tabla_ciudades = ciudades_unicas[['id_ciudad', 'CiudadSucursal']]
print (tabla_ciudades)
#verificamos consistencia de los datos
tabla_ciudades.info()
tabla_ciudades.isnull()
# exportams a csv
#tabla_ciudades.to_csv("D:/soyhenry/m3/pi/ciudades.csv", index=False)

   id_ciudad CiudadSucursal
0          1         Bogotá
1          2           Cali
2          3       Medellín
3          4        Pereíra
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_ciudad       4 non-null      int64
 1   CiudadSucursal  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

   id_ciudad  CiudadSucursal
0      False           False
1      False           False
2      False           False
3      False           False

Clientes
=

In [3]:

#clientes
Clientes = ['ClienteNombre','GeneroCliente','EdadCliente','EmailCliente','TelefonoCliente','DireccionCliente']
Todos_Clientes = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=Clientes)
Clientes_unicos = Todos_Clientes.drop_duplicates(subset=['ClienteNombre']).sort_values('ClienteNombre').reset_index(drop=True)
Clientes_unicos['id_cliente'] = Clientes_unicos.index + 1
tabla_Clientes = Clientes_unicos[['id_cliente','ClienteNombre','GeneroCliente','EdadCliente','EmailCliente','TelefonoCliente','DireccionCliente']]
#print (tabla_Clientes)
#verificamos consistencia de los datos
tabla_Clientes.info()
tabla_Clientes.isnull()
# exportams a csv
#tabla_Clientes.to_csv("D:/soyhenry/m3/pi/clientes.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17449 entries, 0 to 17448
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        17449 non-null  int64
 1   ClienteNombre     17449 non-null  object
 2   GeneroCliente     17449 non-null  object
 3   EdadCliente       17449 non-null  int64
 4   EmailCliente      17449 non-null  object
 5   TelefonoCliente   17449 non-null  object
 6   DireccionCliente  17449 non-null  object
dtypes: int64(2), object(5)
memory usage: 954.4+ KB

,id_cliente,ClienteNombre,GeneroCliente,EdadCliente,EmailCliente,TelefonoCliente,DireccionCliente
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
17444,False,False,False,False,False,False,False
17445,False,False,False,False,False,False,False
17446,False,False,False,False,False,False,False
17447,False,False,False,False,False,False,False
17448,False,False,False,False,False,False,False

Metodo Pago
=

In [5]:
# Metodo Pago
metodoPago = ['MetodoPago']
todos_metodoPago = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=metodoPago)
metodoPago_unicos = todos_metodoPago.drop_duplicates().sort_values('MetodoPago').reset_index(drop=True)
metodoPago_unicos['id_MetodoPago'] = metodoPago_unicos.index + 1
tabla_metodoPago = metodoPago_unicos[['id_MetodoPago', 'MetodoPago']]
#print (tabla_metodoPago)
#verificamos consistencia de los datos
tabla_metodoPago.info()
tabla_metodoPago.isnull()
# exportams a csv
#tabla_metodoPago.to_csv("D:/soyhenry/m3/pi/metodos_pago.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_MetodoPago  6 non-null      int64
 1   MetodoPago     6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

   id_MetodoPago  MetodoPago
0          False       False
1          False       False
2          False       False
3          False       False
4          False       False
5          False       False

Sucursales
=

- Obtenemos las sucursales

In [6]:
# Sucursales
sucursales = ['SucursalNombre', 'CiudadSucursal']
todos_sucursales = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=sucursales)
sucursales_unicos = todos_sucursales.drop_duplicates().sort_values('SucursalNombre').reset_index(drop=True)
sucursales_unicos['id_sucursal'] = sucursales_unicos.index + 1
tabla_sucursales = sucursales_unicos[['id_sucursal', 'SucursalNombre','CiudadSucursal']]
print (tabla_sucursales)

   id_sucursal        SucursalNombre CiudadSucursal
0            1    TechCore Bogotá #1         Bogotá
1            2    TechCore Bogotá #2         Bogotá
2            3         TechCore Cali           Cali
3            4  TechCore Medellín #1       Medellín
4            5  TechCore Medellín #2       Medellín
5            6      TechCore Pereíra        Pereíra

- Vamos a actualizar la tabla sucursales, para que tengo id_ciudad que corresponde, en lugar del nombre de la ciudad

In [7]:
#  Juntamos las dos tablas por la columna 'CiudadSucursal'
df_resultado = pd.merge(tabla_ciudades, tabla_sucursales, on='CiudadSucursal', how='left')
#print (df_resultado)

# slimino la columna que sobra CiudadSucursal
df_resultado = df_resultado.drop(columns=['CiudadSucursal'])
# ordeno las columnas 
tabla_sucursales_final = df_resultado[['id_sucursal', 'SucursalNombre','id_ciudad']]

#print (tabla_sucursales_final)
# #verificamos consistencia de los datos
tabla_sucursales_final.info()
tabla_sucursales_final.isnull()
# exportams a csv
#tabla_sucursales_final.to_csv("D:/soyhenry/m3/pi/sucursales.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_sucursal     6 non-null      int64
 1   SucursalNombre  6 non-null      object
 2   id_ciudad       6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

   id_sucursal  SucursalNombre  id_ciudad
0        False           False      False
1        False           False      False
2        False           False      False
3        False           False      False
4        False           False      False
5        False           False      False

Vendedor
=

- Obtenermos los vendedores

In [8]:
# Vendedores
vendedores = ['VendedorNombre','SucursalNombre']
todos_vendedores = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=vendedores)
vendedores_unicos = todos_vendedores.drop_duplicates().sort_values('VendedorNombre').reset_index(drop=True)
vendedores_unicos['id_vendedor'] = vendedores_unicos.index + 1
tabla_vendedores = vendedores_unicos[['id_vendedor', 'VendedorNombre','SucursalNombre']]
#print (tabla_vendedores)

- Vamos a actualizar la tabla vendedores, para que tengo id_sucursale que corresponde, en lugar del nombre de la sucursal

In [9]:
#  Juntamos las dos tablas por la columna 'SucursalNombre'
df_resultado = pd.merge(tabla_vendedores, tabla_sucursales, on='SucursalNombre', how='left')
#print (df_resultado)

# elimino la columna que sobra SucursalNombre
df_resultado = df_resultado.drop(columns=['SucursalNombre'])
# ordeno las columnas 
tabla_vendedores_final = df_resultado[['id_vendedor', 'VendedorNombre','id_sucursal']]

#print (tabla_vendedores_final)
#verificamos consistencia de los datos
tabla_vendedores_final.info()
tabla_vendedores_final.isnull()

# exportams a csv
#tabla_vendedores_final.to_csv("D:/soyhenry/m3/pi/vendedores.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_vendedor     30 non-null     int64
 1   VendedorNombre  30 non-null     object
 2   id_sucursal     30 non-null     int64
dtypes: int64(2), object(1)
memory usage: 852.0+ bytes

    id_vendedor  VendedorNombre  id_sucursal
0         False           False        False
1         False           False        False
2         False           False        False
3         False           False        False
4         False           False        False
5         False           False        False
6         False           False        False
7         False           False        False
8         False           False        False
9         False           False        False
10        False           False        False
11        False           False        False
12        False           False        False
13        False           False        False
14        False           False        False
15        False           False        False
16        False           False        False
17        False           False        False
18        False           False        False
19        False           False        False
20        False           False        False
21        False           False        False
22        False           False        False
23        False           False        False
24        False           False        False
25        False           False        False
26        False           False        False
27        False           False        False
28        False           False        False
29        False           False        False

Productos
=

In [10]:
#Obtengo las lsitas de los 3 productos
#productos1
Productos1 = ['NombreProducto1','MarcaProducto1','PrecioUnitarioProducto1']
Todos_Productos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=Productos1, low_memory=False)
Productos_unicos = Todos_Productos.dropna().drop_duplicates().sort_values('NombreProducto1') #.reset_index(drop=True)
#Productos_unicos['id_producto'] = Productos_unicos.index + 1
tabla_Productos1 = Productos_unicos[['NombreProducto1','MarcaProducto1','PrecioUnitarioProducto1']].rename (columns= {"NombreProducto1": "NombreProducto", "MarcaProducto1": "MarcaProducto", "PrecioUnitarioProducto1": "PrecioUnitarioProducto"})
#print (tabla_Productos1)

#productos2
Productos2 = ['NombreProducto2','MarcaProducto2','PrecioUnitarioProducto2']
Todos_Productos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=Productos2, low_memory=False)
Productos_unicos = Todos_Productos.dropna().drop_duplicates().sort_values('NombreProducto2') #.reset_index(drop=True)
#Productos_unicos['id_producto'] = Productos_unicos.index + 1
tabla_Productos2 = Productos_unicos[['NombreProducto2','MarcaProducto2','PrecioUnitarioProducto2']].rename (columns= {"NombreProducto2": "NombreProducto", "MarcaProducto2": "MarcaProducto", "PrecioUnitarioProducto2": "PrecioUnitarioProducto"})
#print (tabla_Productos2)

#productos3
Productos3 = ['NombreProducto3','MarcaProducto3','PrecioUnitarioProducto3']
Todos_Productos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=Productos3, low_memory=False)
Productos_unicos = Todos_Productos.dropna().drop_duplicates().sort_values('NombreProducto3') #.reset_index(drop=True)
#Productos_unicos['id_producto'] = Productos_unicos.index + 1
tabla_Productos3 = Productos_unicos[['NombreProducto3','MarcaProducto3','PrecioUnitarioProducto3']].rename (columns= {"NombreProducto3": "NombreProducto", "MarcaProducto3": "MarcaProducto", "PrecioUnitarioProducto3": "PrecioUnitarioProducto"})
#print (tabla_Productos3)

#unire las 3 tablas de productos en una sola
productos = pd.concat([tabla_Productos1, tabla_Productos2,tabla_Productos3], ignore_index=True).reset_index(drop=True).sort_values('NombreProducto')
#productos=productos.drop_duplicates(subset=['NombreProductNombreProductoo']).reset_index(drop=True)
productos = productos.drop_duplicates('NombreProducto').sort_values('NombreProducto').reset_index(drop=True)

productos['id_producto'] = productos.index + 1
tabla_Productos = productos[['id_producto', 'NombreProducto','MarcaProducto','PrecioUnitarioProducto']]

print (tabla_Productos)

#verificamos consistencia de los datos
tabla_Productos.info()
tabla_Productos.isnull()

    id_producto               NombreProducto MarcaProducto  \
0             1                Acer Aspire 5          Acer
1             2                 Acer Nitro 5          Acer
2             3     Acer Predator Helios 300          Acer
3             4                 Acer Swift 3          Acer
4             5         Apple MacBook Air M1         Apple
5             6         Apple MacBook Pro 14         Apple
6             7         Apple MacBook Pro 16         Apple
7             8                Apple iMac 24         Apple
8             9           Asus ROG Strix G15          Asus
9            10          Asus TUF Gaming A15          Asus
10           11             Asus VivoBook 15          Asus
11           12              Asus ZenBook 14          Asus
12           13           Dell Alienware m15          Dell
13           14             Dell Inspiron 15          Dell
14           15           Dell Latitude 7420          Dell
15           16                  Dell XPS 13          Dell
16           17                   HP Envy 13            HP
17           18                   HP Omen 16            HP
18           19               HP Pavilion 15            HP
19           20              HP Spectre x360            HP
20           21             Lenovo IdeaPad 5        Lenovo
21           22          Lenovo Legion 5 Pro        Lenovo
22           23    Lenovo ThinkPad X1 Carbon        Lenovo
23           24               Lenovo Yoga 7i        Lenovo
24           25              MSI GE76 Raider           MSI
25           26                MSI GF65 Thin           MSI
26           27             MSI GS66 Stealth           MSI
27           28                MSI Modern 14           MSI
28           29     Microsoft Surface Book 3     Microsoft
29           30       Microsoft Surface Go 3     Microsoft
30           31   Microsoft Surface Laptop 4     Microsoft
31           32      Microsoft Surface Pro 9     Microsoft
32           33               Razer Blade 15         Razer
33           34               Razer Blade 17         Razer
34           35       Razer Blade Stealth 13         Razer
35           36                Razer Book 13         Razer
36           37     Samsung Galaxy Book Flex       Samsung
37           38  Samsung Galaxy Book Odyssey       Samsung
38           39      Samsung Galaxy Book Pro       Samsung
39           40  Samsung Galaxy Chromebook 2       Samsung

    PrecioUnitarioProducto
0                2000000.0
1                4000000.0
2                5600000.0
3                2600000.0
4                5500000.0
5                8000000.0
6                9600000.0
7                6400000.0
8                6400000.0
9                4800000.0
10               2400000.0
11               3800000.0
12               8000000.0
13               3000000.0
14               5600000.0
15               4800000.0
16               4000000.0
17               6000000.0
18               3500000.0
19               5200000.0
20               2800000.0
21               7200000.0
22               6800000.0
23               4400000.0
24              10000000.0
25               4400000.0
26               8000000.0
27               2800000.0
28               6400000.0
29               3000000.0
30               5200000.0
31               4400000.0
32               8800000.0
33              10000000.0
34               7200000.0
35               6400000.0
36               5600000.0
37               6800000.0
38               4800000.0
39               2000000.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_producto             40 non-null     int64
 1   NombreProducto          40 non-null     object
 2   MarcaProducto           40 non-null     object
 3   PrecioUnitarioProducto  40 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.4+ KB

    id_producto  NombreProducto  MarcaProducto  PrecioUnitarioProducto
0         False           False          False                   False
1         False           False          False                   False
2         False           False          False                   False
3         False           False          False                   False
4         False           False          False                   False
5         False           False          False                   False
6         False           False          False                   False
7         False           False          False                   False
8         False           False          False                   False
9         False           False          False                   False
10        False           False          False                   False
11        False           False          False                   False
12        False           False          False                   False
13        False           False          False                   False
14        False           False          False                   False
15        False           False          False                   False
16        False           False          False                   False
17        False           False          False                   False
18        False           False          False                   False
19        False           False          False                   False
20        False           False          False                   False
21        False           False          False                   False
22        False           False          False                   False
23        False           False          False                   False
24        False           False          False                   False
25        False           False          False                   False
26        False           False          False                   False
27        False           False          False                   False
28        False           False          False                   False
29        False           False          False                   False
30        False           False          False                   False
31        False           False          False                   False
32        False           False          False                   False
33        False           False          False                   False
34        False           False          False                   False
35        False           False          False                   False
36        False           False          False                   False
37        False           False          False                   False
38        False           False          False                   False
39        False           False          False                   False

Marca
=

- Tomando como base la tabla de productos, donde ya tengo todas las marcas, genero la tabla de marcas

In [11]:
# Marcaa
marca_unicos = tabla_Productos[['MarcaProducto']].dropna().drop_duplicates().sort_values('MarcaProducto').reset_index(drop=True)
marca_unicos['id_Marca'] = marca_unicos.index + 1
tabla_marcas = marca_unicos[['id_Marca', 'MarcaProducto']]
print (tabla_marcas)
#verificamos consistencia de los datos
tabla_marcas.info()
tabla_marcas.isnull()
# exportams a csv
#tabla_marcas.to_csv("D:/soyhenry/m3/pi/marcas.csv", index=False)

   id_Marca MarcaProducto
0         1          Acer
1         2         Apple
2         3          Asus
3         4          Dell
4         5            HP
5         6        Lenovo
6         7           MSI
7         8     Microsoft
8         9         Razer
9        10       Samsung
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_Marca       10 non-null     int64
 1   MarcaProducto  10 non-null     object
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

   id_Marca  MarcaProducto
0     False          False
1     False          False
2     False          False
3     False          False
4     False          False
5     False          False
6     False          False
7     False          False
8     False          False
9     False          False

Productos - Marcas
=

- Considerando Marcas, actaulizamos Productos para que haga referencia al ID DE LA MARCA  en lugar del nombre de la marca

In [12]:
#  Juntamos las dos tablas por la columna 'MarcaProducto'
df_resultado = pd.merge(tabla_Productos, tabla_marcas, on='MarcaProducto', how='left')
#print (df_resultado)

# elimino la columna que sobra MarcaProducto
df_resultado = df_resultado.drop(columns=['MarcaProducto'])
#print (df_resultado)
tabla_Productos_final = df_resultado

#verificamos consistencia de los datos
tabla_Productos_final.info()
tabla_Productos_final.isnull()

# exportams a csv
#tabla_Productos_final.to_csv("D:/soyhenry/m3/pi/productos.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_producto             40 non-null     int64
 1   NombreProducto          40 non-null     object
 2   PrecioUnitarioProducto  40 non-null     float64
 3   id_Marca                40 non-null     int64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.4+ KB

    id_producto  NombreProducto  PrecioUnitarioProducto  id_Marca
0         False           False                   False     False
1         False           False                   False     False
2         False           False                   False     False
3         False           False                   False     False
4         False           False                   False     False
5         False           False                   False     False
6         False           False                   False     False
7         False           False                   False     False
8         False           False                   False     False
9         False           False                   False     False
10        False           False                   False     False
11        False           False                   False     False
12        False           False                   False     False
13        False           False                   False     False
14        False           False                   False     False
15        False           False                   False     False
16        False           False                   False     False
17        False           False                   False     False
18        False           False                   False     False
19        False           False                   False     False
20        False           False                   False     False
21        False           False                   False     False
22        False           False                   False     False
23        False           False                   False     False
24        False           False                   False     False
25        False           False                   False     False
26        False           False                   False     False
27        False           False                   False     False
28        False           False                   False     False
29        False           False                   False     False
30        False           False                   False     False
31        False           False                   False     False
32        False           False                   False     False
33        False           False                   False     False
34        False           False                   False     False
35        False           False                   False     False
36        False           False                   False     False
37        False           False                   False     False
38        False           False                   False     False
39        False           False                   False     False

Facturas Cabecera
=

- Obtengo las cabeceras de las facturas

In [14]:
# Facturas
facturas = ['VentaID','FechaVenta','HoraVenta','SucursalNombre','VendedorNombre','ClienteNombre','MetodoPago','DescuentoVenta','TotalVenta','Año','Mes']
todas_facturas = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=facturas)
facturas_unicas = todas_facturas.drop_duplicates().sort_values('VentaID')
#.reset_index(drop=True)
facturas_unicas['TotalSinDescuento'] = facturas_unicas['TotalVenta']/(1-facturas_unicas['DescuentoVenta'])
facturas_unicas['TotalDescuento'] = facturas_unicas['TotalSinDescuento'] -  facturas_unicas['TotalVenta'] 
tabla_facturas = facturas_unicas[['VentaID','FechaVenta','HoraVenta','SucursalNombre','VendedorNombre','ClienteNombre','MetodoPago','DescuentoVenta','TotalVenta','TotalSinDescuento','TotalDescuento','Año','Mes']]
#print (tabla_facturas)

#convertiremos la fecha
# 1. Creamos un diccionario para traducir los meses al inglés, ya que Pandas busca por defecto en inglés
meses_es = {
    "enero": "January",
    "febrero": "February",
    "marzo": "March",
    "abril": "April",
    "mayo": "May",
    "junio": "June",
    "julio": "July",
    "agosto": "August",
    "septiembre": "September",
    "setiembre": "September",
    "octubre": "October",
    "noviembre": "November",
    "diciembre": "December",
}

# 2. Limpiamos el texto: quitamos el día de la semana (jueves, ) y los conectores "de"
# Nota: Reemplaza 'tu_columna_fecha' por el nombre real de tu columna
tabla_facturas["fecha_limpia"] = (
    tabla_facturas["FechaVenta"]
    .str.split(",")
    .str[-1]
).copy()   # Nos quedamos con " 31 de diciembre de 2015"
tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.replace( " de ", " ", case=False)  # Queda " 31 diciembre 2015"

# 3. Traducimos el mes al inglés usando el diccionario
for es, en in meses_es.items():
    tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.replace(
        es, en, case=False, regex=True
    )
# Aseguramos quitar cualquier espacio extra al inicio o al final

tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.strip()


# Convertir usando formato mixto para que Pandas use su motor inteligente
tabla_facturas["fecha_real"] = pd.to_datetime(
    tabla_facturas["fecha_limpia"], format="mixed", dayfirst=True
)

# Convertir al formato final que necesitas (yyyy/mm/dd)
tabla_facturas["FechaVenta"] = tabla_facturas["fecha_real"].dt.strftime("%d/%m/%Y")
tabla_facturas = tabla_facturas.drop(columns=['fecha_limpia','fecha_real'])
print (tabla_facturas)

#verificamos consistencia de los datos
tabla_facturas.info()
tabla_facturas.isnull()
#obtenemos montos totales, para comparar consistencia con totales de los detalles
total_ventas = tabla_facturas['TotalVenta'].sum()
total_sin_descuento = tabla_facturas['TotalSinDescuento'].sum()
total_descuento = tabla_facturas['TotalDescuento'].sum()
print('Total ventas',total_ventas)
print('Total ventas sin descuento',total_sin_descuento)
print('Total ventas descuento',total_descuento)

C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["fecha_limpia"] = (
C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.replace( " de ", " ", case=False)  # Queda " 31 diciembre 2015"
C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.replace(
C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["fecha_limpia"] = tabla_facturas["fecha_limpia"].str.strip()
C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["fecha_real"] = pd.to_datetime(
C:\Users\Dell\AppData\Local\Temp\ipykernel_11912\1415873346.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_facturas["FechaVenta"] = tabla_facturas["fecha_real"].dt.strftime("%d/%m/%Y")

       VentaID  FechaVenta HoraVenta        SucursalNombre  \
29422        1  31/12/2015  05:42:43      TechCore Pereíra
14196        2  23/03/2019  19:03:21  TechCore Medellín #1
26559        3  23/12/2018  02:32:34  TechCore Medellín #2
14350        4  14/11/2015  00:37:36  TechCore Medellín #2
28394        5  29/11/2016  10:34:20         TechCore Cali
...        ...         ...       ...                   ...
1293     29996  31/12/2020  01:33:17  TechCore Medellín #2
29696    29997  14/07/2017  11:29:20         TechCore Cali
5235     29998  06/04/2019  21:38:27  TechCore Medellín #2
15102    29999  27/12/2024  06:49:00  TechCore Medellín #1
11916    30000  23/03/2022  18:41:51    TechCore Bogotá #1

                  VendedorNombre               ClienteNombre  \
29422     Amílcar Ortega-Alberto       Bienvenida Nebot-Fiol
14196  Ana Sofía Llopis Blázquez         Teófila Bueno-Novoa
26559     Juan José Porcel-Riera    Gilberto Chamorro Catalá
14350     Juan José Porcel-Riera      Máximo Coronado Huerta
28394       Jacinta Juárez Marín                 Yago Oliver
...                          ...                         ...
1293      Juan José Porcel-Riera             Claudio del Amo
29696     Basilio Marcos Barrena  Aurora Alegria Castellanos
5235     Claudia Sastre-Quintero         Paco Olivera Suárez
15102      Dominga del Alcántara        Amílcar Amigó Barrio
11916  Poncio Gabriel Poza Acedo        Macaria Otero Alcalá

              MetodoPago  DescuentoVenta  TotalVenta  TotalSinDescuento  \
29422    Tarjeta Crédito            0.00    31200000         31200000.0
14196  Billetera Digital            0.00    10800000         10800000.0
26559     Tarjeta Débito            0.00    21900000         21900000.0
14350  Billetera Digital            0.00    13600000         13600000.0
28394    Tarjeta Crédito            0.00    13900000         13900000.0
...                  ...             ...         ...                ...
1293     Tarjeta Crédito            0.00     6800000          6800000.0
29696    Tarjeta Crédito            0.00    26400000         26400000.0
5235       Transferencia            0.00     5600000          5600000.0
15102      Transferencia            0.00    10800000         10800000.0
11916      Transferencia            0.05     9025000          9500000.0

       TotalDescuento   Año  Mes
29422             0.0  2015   12
14196             0.0  2019    3
26559             0.0  2018   12
14350             0.0  2015   11
28394             0.0  2016   11
...               ...   ...  ...
1293              0.0  2020   12
29696             0.0  2017    7
5235              0.0  2019    4
15102             0.0  2024   12
11916        475000.0  2022    3

[30000 rows x 13 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 30000 entries, 29422 to 11916
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VentaID            30000 non-null  int64
 1   FechaVenta         30000 non-null  object
 2   HoraVenta          30000 non-null  object
 3   SucursalNombre     30000 non-null  object
 4   VendedorNombre     30000 non-null  object
 5   ClienteNombre      30000 non-null  object
 6   MetodoPago         30000 non-null  object
 7   DescuentoVenta     30000 non-null  float64
 8   TotalVenta         30000 non-null  int64
 9   TotalSinDescuento  30000 non-null  float64
 10  TotalDescuento     30000 non-null  float64
 11  Año                30000 non-null  int64
 12  Mes                30000 non-null  int64
dtypes: float64(3), int64(4), object(6)
memory usage: 3.2+ MB
Total ventas 456491670000
Total ventas sin descuento 468029900000.0
Total ventas descuento 11538230000.0

- Vamos a actualizar la tabla facturas, para que tengo ids que correspondan, en lugar del nombre del metodo de pago, Vendedor, Sucursal, Cliente

In [15]:
#  Juntamos las dos tablas por la columna 'MetodoPago'
df_resultado = tabla_facturas.merge( tabla_metodoPago, on='MetodoPago', how='left')
# elimino la columna que sobra MetodoPago
df_resultado = df_resultado.drop(columns=['MetodoPago'])

#merge con tabla de vendedores
df_resultado = df_resultado.merge(tabla_vendedores_final, on ='VendedorNombre',how ='left')
df_resultado = df_resultado.drop(columns=['VendedorNombre','id_sucursal'])

#merge sucursales
df_resultado = df_resultado.merge(tabla_sucursales_final, on ='SucursalNombre',how ='left')
df_resultado = df_resultado.drop(columns=['SucursalNombre','id_ciudad'])

#merge con tabla de clientes
df_resultado = df_resultado.merge(tabla_Clientes, on='ClienteNombre')
# elimino las columnas de clientes
df_resultado = df_resultado.drop(columns=['ClienteNombre','GeneroCliente','EdadCliente','EmailCliente','TelefonoCliente','DireccionCliente'])

tabla_facturas2 =df_resultado

# #verificamos consistencia de los datos
total_ventas2 = tabla_facturas2['TotalVenta'].sum()
total_sin_descuento2 = tabla_facturas2['TotalSinDescuento'].sum()
total_descuento2 = tabla_facturas2['TotalDescuento'].sum()
print('Total ventas',total_ventas2)
print('Total ventas sin descuento',total_sin_descuento2)
print('Total ventas descuento',total_descuento2)

#exportamos 
#df_resultado.to_csv("D:/soyhenry/m3/pi/facturas.csv", index=False)

Total ventas 456491670000
Total ventas sin descuento 468029900000.0
Total ventas descuento 11538230000.0

Facturas Detalle
=

- Obtengo detalle de las facturas

In [16]:
#Obtengo las lsitas de los 3 productos
#productos1
FProductos1 = ['VentaID','NombreProducto1','CantidadProducto1','SubtotalProducto1','DescuentoVenta']
Todos_FProductos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=FProductos1,low_memory=False)
FProductos_unicos = Todos_FProductos.dropna().drop_duplicates().sort_values('NombreProducto1') #.reset_index(drop=True)
tabla_FProductos1 = FProductos_unicos[['VentaID','NombreProducto1','CantidadProducto1','SubtotalProducto1','DescuentoVenta']].rename (columns= {"NombreProducto1": "NombreProducto", "CantidadProducto1": "CantidadProducto", "SubtotalProducto1": "SubtotalProducto"})
#print (tabla_FProductos1)
#30000
#productos2
FProductos2 = ['VentaID','NombreProducto2','CantidadProducto2','SubtotalProducto2','DescuentoVenta']
Todos_FProductos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=FProductos2,low_memory=False)
FProductos_unicos = Todos_FProductos.dropna().drop_duplicates().sort_values('NombreProducto2') #.reset_index(drop=True)
tabla_FProductos2 = FProductos_unicos[['VentaID','NombreProducto2','CantidadProducto2','SubtotalProducto2','DescuentoVenta']].rename (columns= {"NombreProducto2": "NombreProducto", "CantidadProducto2": "CantidadProducto", "SubtotalProducto2": "SubtotalProducto"})
#print (tabla_FProductos2)
#20012

#productos3
FProductos3 = ['VentaID','NombreProducto3','CantidadProducto3','SubtotalProducto3','DescuentoVenta']
Todos_FProductos = pd.read_csv("D:/soyhenry/m3/pi/ventasTransformed.csv", encoding='UTF-8', usecols=FProductos3,low_memory=False)
FProductos_unicos = Todos_FProductos.dropna().drop_duplicates().sort_values('NombreProducto3') #.reset_index(drop=True)
tabla_FProductos3 = FProductos_unicos[['VentaID','NombreProducto3','CantidadProducto3','SubtotalProducto3','DescuentoVenta']].rename (columns= {"NombreProducto3": "NombreProducto", "CantidadProducto3": "CantidadProducto", "SubtotalProducto3": "SubtotalProducto"})
#print (tabla_FProductos3)
#10047

#unire las 3 tablas de productos en una sola
productos_factura = pd.concat([tabla_FProductos1, tabla_FProductos2,tabla_FProductos3], ignore_index=True).reset_index(drop=True)
productos_factura['id_detalle'] = productos_factura.index + 1
tabla_Productos_factura = productos_factura[['VentaID','id_detalle','NombreProducto','CantidadProducto','SubtotalProducto','DescuentoVenta']]
print(tabla_Productos_factura)

       VentaID  id_detalle               NombreProducto  CantidadProducto  \
0        21666           1                Acer Aspire 5               2.0
1         8451           2                Acer Aspire 5               1.0
2         5074           3                Acer Aspire 5               2.0
3        27444           4                Acer Aspire 5               2.0
4         6073           5                Acer Aspire 5               2.0
...        ...         ...                          ...               ...
60054    20683       60055  Samsung Galaxy Chromebook 2               1.0
60055    19903       60056  Samsung Galaxy Chromebook 2               1.0
60056    17375       60057  Samsung Galaxy Chromebook 2               1.0
60057    22344       60058  Samsung Galaxy Chromebook 2               1.0
60058     4706       60059  Samsung Galaxy Chromebook 2               2.0

       SubtotalProducto  DescuentoVenta
0             4000000.0            0.05
1             2000000.0            0.00
2             4000000.0            0.00
3             4000000.0            0.00
4             4000000.0            0.10
...                 ...             ...
60054         2000000.0            0.00
60055         2000000.0            0.00
60056         2000000.0            0.00
60057         2000000.0            0.00
60058         4000000.0            0.00

[60059 rows x 6 columns]

- Vamos a actualizar la tabla productos de facturas, para que tengo id_producto que corresponde, en lugar del nombre del producto

In [17]:
#  Juntamos las dos tablas por la columna 'nombre de producto'
df_resultado = tabla_Productos_factura.merge( tabla_Productos, on='NombreProducto')
# elimino la columna que sobra MetodoPago
df_resultado = df_resultado.drop(columns=['NombreProducto','MarcaProducto','PrecioUnitarioProducto'])
print (df_resultado)

df_resultado['SubtotalConDescuento'] = df_resultado['SubtotalProducto'] - (df_resultado['DescuentoVenta']*df_resultado['SubtotalProducto'] )
df_resultado['SubtotalDescuento'] = df_resultado['SubtotalProducto'] -  df_resultado['SubtotalConDescuento'] 
#df_resultado = df_resultado[['VentaID','FechaVenta','HoraVenta','SucursalNombre','VendedorNombre','ClienteNombre','MetodoPago','DescuentoVenta','TotalVenta','TotalSinDescuento','TotalDescuento','Año','Mes']]
facturas_detalle=df_resultado
#print (tabla_facturas)

# #verificamos consistencia de los datos
df_resultado.info()
df_resultado.isnull()
total_ventasCD = (df_resultado['SubtotalProducto'] ).sum()
total_ventasSD = (df_resultado['SubtotalConDescuento']  ).sum()
total_ventasSoloD = (df_resultado['SubtotalDescuento']  ).sum()

facturas_detalle=df_resultado

print('Total de ventas de detalle ',total_ventasCD)
print('Total de ventas de detalle ',total_ventasSD)
print('Total de ventas de detalle ',total_ventasSoloD)

#exportamos la tabla
#df_resultado.to_csv("D:/soyhenry/m3/pi/facturas_detalle.csv", index=False)

       VentaID  id_detalle  CantidadProducto  SubtotalProducto  \
0        21666           1               2.0         4000000.0
1         8451           2               1.0         2000000.0
2         5074           3               2.0         4000000.0
3        27444           4               2.0         4000000.0
4         6073           5               2.0         4000000.0
...        ...         ...               ...               ...
60054    20683       60055               1.0         2000000.0
60055    19903       60056               1.0         2000000.0
60056    17375       60057               1.0         2000000.0
60057    22344       60058               1.0         2000000.0
60058     4706       60059               2.0         4000000.0

       DescuentoVenta  id_producto
0                0.05            1
1                0.00            1
2                0.00            1
3                0.00            1
4                0.10            1
...               ...          ...
60054            0.00           40
60055            0.00           40
60056            0.00           40
60057            0.00           40
60058            0.00           40

[60059 rows x 6 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60059 entries, 0 to 60058
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   VentaID               60059 non-null  int64
 1   id_detalle            60059 non-null  int64
 2   CantidadProducto      60059 non-null  float64
 3   SubtotalProducto      60059 non-null  float64
 4   DescuentoVenta        60059 non-null  float64
 5   id_producto           60059 non-null  int64
 6   SubtotalConDescuento  60059 non-null  float64
 7   SubtotalDescuento     60059 non-null  float64
dtypes: float64(5), int64(3)
memory usage: 3.7 MB
Total de ventas de detalle  468029900000.0
Total de ventas de detalle  456491670000.0
Total de ventas de detalle  11538230000.0

Generar XLSX
=

In [18]:
# tabla_Productos_final, tabla_Clientes, tabla_sucursales_final, tabla_facturas2, facturas_detalle, tabla_ciudades, tabla_vendedores_final, 
# tabla_marcas, tabla_metodoPago
#
with pd.ExcelWriter('D:/soyhenry/m3/pi/modeloVentas.xlsx', engine='openpyxl') as writer:

    tabla_Productos_final.to_excel(writer, sheet_name='Productos', index=False)

    tabla_Clientes.to_excel(writer, sheet_name='Clientes', index=False)

    tabla_sucursales_final.to_excel(writer, sheet_name='Sucursales', index=False)

    tabla_facturas2.to_excel(writer, sheet_name='Facturas', index=False)

    facturas_detalle.to_excel(writer, sheet_name='DetalleFacturas', index=False)

    tabla_ciudades.to_excel(writer, sheet_name='Ciudades', index=False)

    tabla_vendedores_final.to_excel(writer, sheet_name='Vendedores', index=False)

    tabla_marcas.to_excel(writer, sheet_name='Marcas', index=False)
    
    tabla_metodoPago.to_excel(writer, sheet_name='MetodoPago', index=False)

    # ... las tabla